#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_DB_MIGRATOR_USER}') THEN
        CREATE ROLE ${APP_DB_MIGRATOR_USER} LOGIN PASSWORD '${APP_DB_MIGRATOR_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_DB_USER}') THEN
        CREATE ROLE ${APP_DB_USER} LOGIN PASSWORD '${APP_DB_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_MIGRATOR_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER};

GRANT USAGE, CREATE ON SCHEMA public TO ${APP_DB_MIGRATOR_USER};
GRANT USAGE ON SCHEMA public TO ${APP_DB_USER};

ALTER SCHEMA public OWNER TO ${APP_DB_MIGRATOR_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_DB_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${APP_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_DB_MIGRATOR_USER} IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${APP_DB_MIGRATOR_USER} IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_DB_USER};
EOSQL